export class Building {}
export class NeutralBuilding extends Building {}
export class BuildingA extends NeutralBuilding {}
export class BuildingB extends NeutralBuilding {}
export class BuildingC extends NeutralBuilding {}
export class BuildingD extends NeutralBuilding {}
export class BuildingE extends NeutralBuilding {}
export class BuildingF extends NeutralBuilding {}
export class BuildingG extends NeutralBuilding {}
export class BuildingH extends NeutralBuilding {}
export class PlayerBuilding extends NeutralBuilding {}
export class Building1A extends PlayerBuilding {}
export class Building2A extends PlayerBuilding {}
export class Building3A extends PlayerBuilding {}
export class Building4A extends PlayerBuilding {}
export class Building5A extends PlayerBuilding {}
export class Building6A extends PlayerBuilding {}
export class Building7A extends PlayerBuilding {}
export class Building8A extends PlayerBuilding {}
export class Building9A extends PlayerBuilding {}
export class Building10A extends PlayerBuilding {}
export class Building1B extends PlayerBuilding {}
export class Building2B extends PlayerBuilding {}
export class Building3B extends PlayerBuilding {}
export class Building4B extends PlayerBuilding {}
export class Building5B extends PlayerBuilding {}
export class Building6B extends PlayerBuilding {}
export class Building7B extends PlayerBuilding {}
export class Building8B extends PlayerBuilding {}
export class Building9B extends PlayerBuilding {}
export class Building10B extends PlayerBuilding {}
export class NoBuilding extends NeutralBuilding {}
